language: node_js
node_js: node
cache:
  directories:
  - node_modules
env:
- CI=true
deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: rlBVd5RdqtNZ4mVKPt+QR8OIW2bdwyJikU8awwkb/21X5YVyPR52u+rzI5S8ued6RBaQ2El+SSmYUc+53njzsPQY7K7TpzCxgiEEe66CqgOzna9ubl7J+5dBTWpzxZC22o1HWiDmE68XKxsBpK9+7Ko/jagsyTZMQoIlmRmMieZXf77fQcNhNVIbW8IRCUChKsv8FSLEd0oj6dK42Z1gL4ptfqBrOvDs2X/xTqtFssa49CZcDjUlYNc4gvIdpnqHY4soBlkVs18V9KaSuGoRgIRBPj3eSzXnGKi44qo2iZ2mA2rV/7EVWOwIWXkIb4HilMn+Auappc3bO4iIM3DQOfOFQqgmegH49Oeqm2rAURL/tK6JhgD/pqsqbZNpWtygS11hdj3VyGhWqkmqWAUSYWB7CZna7mdSxHO1YnYehCAie7JyQn1mpqxjK3huGVj1Qr1G0UXgScLjk6WyZ93kfwEMKoxjPG2Jm5ntg5GfJrWVFWDyniYuxwhKzUUP3uorC1kSKnnF5VBw+V9eBHTYnwx02vIQj4UdyqOEfqkyTK1eOb1fb2ItZ4woIXD3rQIYQVGjal9v0zrrmHemXuJxCveqflTgQ9aVpRoyUWuBKNr3Wux8iv9l+i+IZLr/GrCYG9q9iCJmwusnx69oGY481g6kqmHMr61pGXIH0h4j2+Y=
  app: fathomless-brook-48599
  on:
    repo: smr310/travelbak-client     
